export const messageTypes = {
    NOTIFY_USER: "NOTIFY_USER",
    TAB_LOADED_URL: "TAB_LOADED_URL",
    SITES_UPDATED: "SITE_UPDATED",
    LIMITS_UPDATED: "LIMITS_UPDATED",
    REPORT_CATEGORIES_UPDATED: "REPORT_CATEGORIES_UPDATED",
    SEND_LIMITS: "SEND_LIMITS",
    SHOW_IN_MODAL: "SHOW_IN_MODAL",
    GENERATE_WORDCLOUD_FOR_SITE: "GENERATE_WORDCLOUD_FOR_SITE",
    IS_SITE_SUPPORTED: "IS_SITE_SUPPORTED",
    TOGGLE_CONTEXT_MENU: "TOGGLE_CONTEXT_MENU",
    SUBMIT: "SUBMIT",
    FETCH_ARTICLE: "FETCH_ARTICLE",
    WORDCLOUD_FOR_ARTICLE: "WORDCLOUD_FOR_ARTICLE",
    FETCH_INFO_FOR_LINKS: "FETCH_INFO_FOR_LINKS",
    NOTIFY_DEV: "NOTIFY_DEV"
};

export function createMessage(type: string, data = {}) {
    return {
        type: type,
        data: data
    }
}